[project]
name = "python-chat-Bilaljanir"
version = "0.1.0"
description = "Chat en temps réel dans le terminal, basé sur des sockets TCP"
readme = "README.md"
authors = [
    { name = "Bilal Janir", email = "bilaljanir@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "rich>=15.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.4",
]

[tool.uv]
package = false
